name: Node.js CI

on:
    push:
        branches: ['master']
    pull_request:
        branches: ['master']

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [20.x]

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'

            - name: Clean npm cache
              run: npm cache clean --force

            - name: Install dependencies
              run: |
                  for i in {1..3}; do npm install --legacy-peer-deps && break || sleep 5; done

            - name: Build Project
              run: npm run build --if-present

            - name: Run Tests
              run: npm test
