name: Node.js CI

on:
    push:
        branches: ['master']
    pull_request:
        branches: ['master']

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [20.8.1] # 指定为 Node.js 20.8.1

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'

            - name: Clean npm cache and reinstall dependencies
              run: |
                  rm -rf node_modules package-lock.json
                  npm cache clean --force
                  npm install --legacy-peer-deps

            - name: Build Project
              run: npm run build --if-present

            - name: Run Tests
              run: npm test
