name: Node.js CI

on:
    push:
        branches: ['master']
    pull_request:
        branches: ['master']

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [20.8.1]

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0  # 确保完整克隆

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'

            - name: Clean and Install Dependencies
              run: |
                  rm -rf node_modules package-lock.json
                  npm cache clean --force
                  npm install --legacy-peer-deps

            - name: Install Jest (if not included)
              run: npm install --save-dev jest

            - name: Build Project
              run: npm run build --if-present

            - name: Run Tests
              run: npm test

            - name: SSH Setup & Deploy
              uses: appleboy/scp-action@v0.1.7
              with:
                  host: ${{ secrets.SERVER_IP }}
                  username: root
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  source: ./dist/*
                  target: /var/www/html/

            - name: Push to Gitee1
              run: |
                  git config --global user.name "xing-hao-dong"
                  git config --global user.email "975115611@qq.com"

                  # 添加 Gitee 远程仓库
                  git remote add gitee https://gitee.com/xing-hao-dong/vue-vite.git
                  
                  # 提交所有修改 (包括构建后的文件)
                  git add -A
                  git commit -m "CI: Auto-commit changes before pushing to Gitee" || echo "No changes to commit"

                  # 拉取 Gitee 仓库的完整历史并合并
                  git fetch gitee
                  git pull --rebase gitee master || echo "No rebase necessary"

                  # 推送更改到 Gitee 仓库
                  git push https://oauth2:${{ secrets.GITEE_TOKEN }}@gitee.com/xing-hao-dong/vue-vite.git HEAD:master -f
