name: Node.js CI

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.8.1]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Clean and Install Dependencies
        run: |
          rm -rf node_modules package-lock.json
          npm cache clean --force
          npm install --legacy-peer-deps

      - name: Install Jest (if not included)
        run: npm install --save-dev jest

      - name: Build Project
        run: npm run build --if-present

      - name: Run Tests
        run: npm test

      - name: Create SSH Directory
        run: mkdir -p ~/.ssh

      - name: Add Known Hosts
        run: ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Set Permissions for Known Hosts
        run: chmod 644 ~/.ssh/known_hosts

      - name: Deploy to Server using SCP
        run: |
          scp -o StrictHostKeyChecking=no -i /tmp/id_rsa ./dist/* root@${{ secrets.SERVER_IP }}:/var/www/html/
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Write SSH Private Key to File
        run: echo "$SSH_PRIVATE_KEY" > /tmp/id_rsa
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Set Permissions for SSH Private Key
        run: chmod 600 /tmp/id_rsa
