name: Node.js CI

on:
    push:
        branches: ['master']
    pull_request:
        branches: ['master']

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [20.8.1]

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'

            - name: Clean and Install Dependencies
              run: |
                  rm -rf node_modules package-lock.json
                  npm cache clean --force
                  npm install --legacy-peer-deps

            - name: Install Jest (if not included)
              run: npm install --save-dev jest

            - name: Build Project
              run: npm run build --if-present

            - name: Run Tests
              run: npm test

            - name: Set up SSH agent
              run: eval "$(ssh-agent -s)"

            - name: Add SSH private key to the agent store
              run: ssh-add - <<< "$SSH_PRIVATE_KEY"
              env:
                  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

            - name: Known Hosts
              run: ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

            - name: Deploy to Server
              uses: appleboy/scp-action@v0.1.0 # 推荐指定版本
              with:
                  host: ${{ secrets.SERVER_IP }}
                  username: root
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  source: './dist/*' # 确保正确传递路径
                  target: '/var/www/html/' # 目标路径
